### ISSUE TITLE
Select only correct field on querying model

### ISSUE THREAD

**Issue by dorianamouroux** [codingjoe/django-stdimage#101]
Hi,

I'm using Django-stdimage and I changed the variations of one of my image field. I decided to run the `rendervariations` in a migration file.
It works perfectly, but then I added more migrations file for other changes. When I wanted to deploy it, my rendervariation migration script didn't work.
The other fields I added in the model didn't exist in the database yet because it was on further migration. I think if the query just select the required field, it would work.

**Comment by codingjoe** [comment]
I don't know if I fully understand you. Can you explain a bit more what you did? Thanks!
