### ISSUE TITLE
Rescale uploaded image before actual saving

### ISSUE THREAD

**Issue by marojenka** [codingjoe/django-stdimage#107]
Hi,
in order to save space on the hard drive I was looking how to get rid off unnecessary big original images. 
As I understood it's not desirable behavior so I was hoping for a criticism of my workaround:
[Gist](https://gist.github.com/marojenka/722a1dc674490a514cfbbe5ee449cc79)

I'm not so good with python so might miss simpler way. 

Anyway, love this project!

**Comment by codingjoe** [comment]
@marojenka hi, thanks for reaching out. I think your solution is fine. We keep the original, because on a production scale, disk space is really cheap. It's more valuable for your business to keep the original user data for future purpose. Like increasing pixel density and so on.

**Comment by marojenka** [comment]
thanks. 
Clearly you are right about disk space and I didn't expect it to go into main branch. 
But it's a way to make any kind of changes for uploaded image so may be someone will find it useful.

**Comment by jamesfebin** [comment]
I understand this library doesn't support deleting of original files.  But is there any way to do it manually?

**Comment by codingjoe** [comment]
Sure, but it isn't simple. Because a lot of features rely on keeping the original, like rerendering. What's your use case?
