### ISSUE TITLE
Get all variations in serializer

### ISSUE THREAD

**Issue by BojanKogoj** [codingjoe/django-stdimage#119]
I have a REST API, and would like to get all variations. 

Right now I only get
`"picture": "/media/pictures/f80032bde14c4040bb1d24c270c5ad45.png",`
which is the original, but I would like to get all variations in the response as well (large, medium, thumbnail). How would I get that with a serializer?

**Comment by codingjoe** [comment]
hi @BojanKogoj , I guess you are looking for this:
https://github.com/glemmaPaul/django-stdimage-serializer

**Comment by BojanKogoj** [comment]
That's exactly what I needed, thanks! Maybe add it to documentation for others?

**Comment by codingjoe** [comment]
I wanted to merge this into this package, but there has been no effort from the maintainer yet.
