### ISSUE TITLE
Windows does not support resource module

### ISSUE THREAD

**Issue by foxbunny** [codingjoe/django-stdimage#127]
While django-stdimage works very well in general, rendervariations breaks due to `ModuleNotFoundError`.

```
File "C:\path\to\env\lib\site-packages\stdimage\management\commands\rendervariations.py", line 4, in <module>
ModuleNotFoundError: No module named 'resource'
```

It's probably not a big issue if memory usage would just say n/a on Windows, and wrap the import in `try except`? If this sounds like a good idea, I could do a pull request.

**Comment by codingjoe** [comment]
Hi @foxbunny thanks for the bug report. I don't have a windows PC at my hands right now. I would love to get a PR from your side fixing this issue.

Thanks!

**Comment by foxbunny** [comment]
Sure thing. I'll send a PR.
