### ISSUE TITLE
Image names

### ISSUE THREAD

**Issue by Baevra** [codingjoe/django-stdimage#171]
How can i achieve such file names like filename@3x.jpeg (for original), filename@2x.jpeg (variation), filename.jpeg (variation). By default original image has no postfix and i want to add it.

Thanks

**Comment by codingjoe** [comment]
Hi @Baevra, I guess you want to do that for hi-res display right?
Well what you can do is add variations for like so:

```python
variations = {
    '3x',
    '2x',
    '1x',
}
```

I can not recommend to use the original image. How do you ensure it is of the right size, JPEG quality and so on. You will also need to change this method and replace the dot with an `@`-sign:
https://github.com/codingjoe/django-stdimage/blob/1f2d3f8b8129f9dabd1572883ba526dfae46fd86/stdimage/models.py#L124-L134
