### ISSUE TITLE
Async image processing - storage not serializable

### ISSUE THREAD

**Issue by radzak** [codingjoe/django-stdimage#173]
I tried to process images asynchronously with Celery, followed the example and encountered an error:

`Exception Type: EncodeError`
`Exception Value: <django.core.files.storage.DefaultStorage object at 0x7f3c9052cf28> is not JSON serializable
`

The fix I found was not to pass storage to the task function:
```python
def image_processor(file_name, variations, storage):
    process_photo_image.delay(file_name, variations)
    return False  # prevent default rendering
```
and the task itself looks like:
```python
@shared_task
def process_photo_image(file_name, variations):
    render_variations(file_name, variations, replace=True)
```
Now it works fine, but there are two issues with that solution. Firstly, it's not possible to use other storage than the default one, since you can't pass it to the 'task function' as an argument. Secondly, I don't like the unused parameter in image_processor function.

I couldn't come up with any reasonable fix myself, so I open an issue.

#### Environment
Python 3.6.2
django==1.11.7
celery==4.1.0
django-stdimage==2.4.2

**Comment by codingjoe** [comment]
Hi @radzak I would welcome a patch a lot! If you already have an idea the better! My best guess would be to pass the storage import path and [load it again](https://docs.djangoproject.com/en/1.11/ref/files/storage/#getting-the-current-storage-class) in celery.
