### ISSUE TITLE
Redefining image paths

### ISSUE THREAD

**Issue by webtweakers** [codingjoe/django-stdimage#183]
I have a Django Model with a StdImage field, like this:

```python
image = StdImageField(upload_to=UploadToUUID(path='poster'), blank=True, variations={
    'w250': {'width': 250, 'height': 370},
    'w500': {'width': 500, 'height': 740},
})
```

I would like to be able to store the images in paths like this:

```
.../media/poster/w250/8/82036b3e13e370d604816b4918a3ee30.jpg
.../media/poster/w500/8/82036b3e13e370d604816b4918a3ee30.jpg
.../media/poster/original/8/82036b3e13e370d604816b4918a3ee30.jpg
```

I'm looking at the code and particularly at `get_variation_name` in `StdImageFieldFile` and the `Upload` classes in `utils`, but I'm unsure how to accomplish this.

I suppose I could override `get_variation_name` and alter how the variation name is created, but I'm uncertain how the upload_to path (`poster`) fits in there and how to change the path of the original (large) image file.

Any suggestions?

**Comment by codingjoe** [comment]
@webtweakers yes, that presume this would be the way to go. I never thought about folders. As I mostly use a key-value store like S3.

**Comment by webtweakers** [comment]
Using the variation name in the path like that (.../media/poster/**_w500_**/8/82036b3e13e370d604816b4918a3ee30.jpg) was not so straight-forward, so I left the `get_variation_name` as is.

I just made my own version of UploadToUUID that takes care of at least adding one sub-path to the name, which is enough. It goes something like this, for future reference:

```python
import os
import uuid

from stdimage.utils import UploadTo


class UploadToPathUUID(UploadTo):
    def __call__(self, instance, filename):
        u = uuid.uuid4().hex
        self.kwargs.update({
            'name': os.path.join(u[0], u),
        })
        return super().__call__(instance, filename)
```

**Comment by codingjoe** [comment]
Thanks for sharing that. It's good to have it as documentation for other 👍
