### ISSUE TITLE
Is python2 supported?

### ISSUE THREAD

**Issue by mthaddon** [codingjoe/django-stdimage#196]
Hi,

From looking at commit history I see https://github.com/codingjoe/django-stdimage/commit/7ccffc699bfe7b2ffe6a457c286f3f98f2f98c42 has a commit message of "Remove Python 2 support". However "sudo pip install django-stdimage" gave me /usr/local/lib/python2.7/dist-packages/stdimage/. This is version 3.2.0.

When I run my project, which imports stdimage as outlined in the readme I get:

TypeError: super() takes at least 1 argument (0 given)

I assume this is a Python3 vs. Python2 issue.

I'm running Django 1.11.11. The field that's triggering this error is:

uploadedimage = StdImageField(upload_to=UploadToUUID(path="personimage"), blank=True,
                                   variations={
                                       'large': (2500, 1500),
                                       'medium': (640, 480),
                                       })

Thanks, Tom

**Comment by codingjoe** [comment]
td;dr

Hi @mthaddon thanks for reaching out!
The short answer is **no**, see also https://github.com/codingjoe/django-stdimage/releases/tag/3.0.0
If you want to use Python 2 (which I would not recommend) you can use any version prior to v3.

Best -Joe
