### ISSUE TITLE
Additional query when using only()

### ISSUE THREAD

**Issue by jmaslanka** [codingjoe/django-stdimage#203]
Hello!

I have added StdImageField to a model, simple one:
```
photo = StdImageField(
    verbose_name=_('image'),
    upload_to=UploadToClassNameDirUUID(),
    blank=True,
)
```

When I do a query on that model with `only('<some_other_field>')` Django will create additional query to fetch an image:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/12375470/48901933-401ce100-ee57-11e8-9b54-0179be251edf.png">

Is is possible to avoid that fetch? I know I could just add `photo` to `only()` but it's a workaround that would only create confusion in my code.

**Comment by codingjoe** [comment]
Hi @jmaslanka thanks for reaching out. Good catch, I didn't see this one before, but it makes sense. This certainly is a bug.
