### ISSUE TITLE
DoesNotExist exception when retrieving instance from processing task

### ISSUE THREAD

**Issue by frossigneux** [codingjoe/django-stdimage#205]
I have an asynchronous task to process images.

I get a DoesNotExist exception when I try to get the Photo instance.
So I cannot update instance fields from my task.
With pdb, I see that "save" is False upper in the stack trace. So I think the object is not yet created.

```
django/db/models/fields/files.py(288)pre_save()
-> file.save(file.name, file.file, save=False)
(Pdb) l
284  	    def pre_save(self, model_instance, add):
285  	        file = super().pre_save(model_instance, add)
286  	        if file and not file._committed:
287  	            # Commit the file to storage prior to saving the model
288  ->	            file.save(file.name, file.file, save=False)
289  	        return file
```

I have a custom serializer like this:
```
    def create(self, validated_data):
        user = self.context["request"].user
        # Some lines...
        photo = Photo.objects.create(user=user, **validated_data)  # Triggers the task
```

The problem occurs with both:
- local SQLite / Google SQL database
- synchronous / asynchronous execution of the task.

To retrieve the Photo instance from my task, I tried:
`obj = models.Photo.objects.get(image=file_name)
`
as well as
`obj = apps.get_model('myapp', 'Photo').objects.get(image=file_name)`

I don't use Celery but https://github.com/GeorgeLubaretsi/django-cloud-tasks, but it doesn't matter I guess.

I see in the doc: "Note that the callback is not transaction save, but the file will be there". Do you mean that there is no guarantee that your task example updates the "processed" field, if this line may fail?
`obj = apps.get_model('myapp', 'Photo').objects.get(image=file_name)`

Thanks

**Comment by codingjoe** [comment]
Hi @frossigneux, thanks for reaching out. Let's see... it seems you are running into a race condition, in which your database record is not yet saved before you try to access it. That is a very common issue.
The trick is to use the [on_commit](https://docs.djangoproject.com/en/2.1/topics/db/transactions/#performing-actions-after-commit) transaction hook. This allows you to execute code after your database transaction is committed.
In slightly simpler terms, your asynchronous task engine is faster than your database. The worker that processes your image rendering tries to access a record that is not yet persisted on your database.
If your database adapter does not support the `on_commit` transaction hook, all you can do is backoff and retry the task.

I hope that helped a bit. Let me know if you have any further questions.

Merry Xmas!
-Joe
