### ISSUE TITLE
Default image should not be removed with delete_orphans.

### ISSUE THREAD

**Issue by jckw** [codingjoe/django-stdimage#216]
A model that uses both a default image and delete_orphans=True will delete the default image if it is changed.

This is bad because the default image is designed to be shared across many users, as well as staying in the media when no users are using it. An exception should be made for delete_orphans if the file is the default image as it is a special case. 

Example model:
```python 
class User(models.Model):
    profile_image = StdImageField(
        upload_to="users/profile_images/",
        default="users/profile_images/default.png",
        max_length=300,
        blank=False,
        null=False,
    )
```

i.e. default.png should remain untouched regardless of other changes.

**Comment by codingjoe** [comment]
Hi @jckw thanks for reaching out. I think I need a bit more information about your scenario to figure out the best solution. In any case, you can always subclass and implement the desired behavior yourself. In fact, I would probably recommend that in most cases unless they are very common.

Anyhow, let me go ahead and explain the current behavior, to give you a better idea about why things are implemented as the currently are.

The `delete_orphans` feature is rather new and replaced optional `pre_save` and `post_delete` event listeners. They simply to called `delete` on the `FieldFile` which is the object you get, when accessing a field attribute on a model. That is pretty much was `delete_orphans` does too. It calls `FieldFile.delete()` and the `FieldFile` implementation decides what files to delete and which it doesn't.
The `StdImageFieldFile` calls super, which deletes the original file and deletes all variations. So in a way, you want to change Django's behavior, not the one of this package.

Knowing all that, I would go ahead, and implement something like this:

```python
from stdimage.models import StdImageField, StdImageFieldFile

class MyImageFieldFile(StdImageFieldFile):
    def delete(self):
        pass  # implement your wanted behavior here


class MyImageField(StdImageField):
    attr_class = MyImageFieldFile
```

I must caution you though. The regular `FileSystemStorage` in Django will not override files. So given your `default` is a string. The first time you upload a file, it will take that name. Once the file name is "taken", Django will append a random bit, to the end of the file name.
Should you be using the AWS S3 storage backend provided by `django-storages`, it behaves differently and will silently override files. You can change that via a setting. Just be extra careful and maybe reconsider your implementation, given what you want to achieve.

Anyhow, I hope that server you as a start. I am curious to understand better, what you're currently trying to accomplish.

Best
-Joe

**Comment by jckw** [comment]
Hey Joe, 

Thanks for getting back to me with such a thorough explanation! (And sorry about my slow reply)

The implementation I'm trying to achieve is similar to what you might see on Twitter. The default profile image is the [egg](https://www.merriam-webster.com/words-at-play/which-came-first-the-twitter-chicken-or-the-twitter-egg), and then users are free to upload their own images as a replacement. We use `delete_orphans` since we don't want to save every profile picture a user has, but just the current one (there's no where to see the previous ones anyway).

We also don't want to save the default profile image multiple times, since we know it's fixed. Therefore many more users can be created and all have the default profile image (referencing the same file).

Finally, we also don't want files to be overwritten, since two users could upload different images with the same name (and at the moment we're preserving that name, although I'm happy to use a UUID or similar).

Hopefully that explains the user case a little more, and makes it seem like a potentially popular use case.

We're also using Django Storages (but with GCloud).

I guess one possibility from what you've suggested is that I have the delete method on the FieldFile check if the file is the special reserved-name default file, and not delete if that's the case. That would be okay, but it does seem a somewhat fragile.

**Comment by codingjoe** [comment]
Hi @jckw 
Interesting use case. I believe in this case I would implement the default not via the file field, but though a property or a template if-clause.

Something like:

```python
from django.contrib.staticfiles.storage import staticfiles_storage
from django.db import models
from stdimage.models import StdImageField


class UserProfile(models.Model):
    image = StdImageField(upload_to='profile-pictures/', delete_orphans=True, variations={'thumb': (320, 320)})

    @property
    def image_url(self):
        if self.image:
            return self.image.thumb.url
        return staticfiles_storage.url('img/default_profile_picture.png')
```

In you template would only use `{{ obj.img_url }}`.

Does that solve your problem?

Best,
Joe
