### ISSUE TITLE
Dynamically set variations for a StdImageField

### ISSUE THREAD

**Issue by baxeico** [codingjoe/django-stdimage#254]
This is a question and not an issue. Hope that this is the right place to ask. :)

Imagine a model like this.

```
class MovieImage(TimeStampedModel):
    IMAGE_TYPE_CHOICES = Choices('logo', 'cover')
    movie = models.ForeignKey(Movie, related_name='images', on_delete=models.CASCADE)
    image = StdImageField(upload_to='movies/', max_length=100)
    image_type = models.CharField(choices=IMAGE_TYPE_CHOICES, max_length=30, blank=True)
```

I would like to have different variations basing on `image_type`. Could the variation attribute be specified at runtime, e.g. on a Django view?

Thank you very much for your help and keep up the good work!

**Comment by codingjoe** [comment]
Hi @baxeico,

Thank you for reaching out. I am afraid this isn't possible right now and probably never will. This package is meant for applications where pictures are rendered into different sizes in advance and not during a request. However, there are other libraries for those kinds of scenarios. However, this might not be the perfect one.

Best,
Joe

**Comment by baxeico** [comment]
Thank you!
