### ISSUE TITLE
JPEGField does not replace .jpg with .jpeg and results in wrong path

### ISSUE THREAD

**Issue by tgdn** [codingjoe/django-stdimage#255]
Version: v5.3.1
Django version: v3.2.5

When using the above versions, and using a `JPEGField`, after uploading an image with extension ".jpg", it is not accessible using the path/url attribute as it replaces/forces .jpeg instead of .jpg.

This has multiple consequences:

- `delete_orphans` does not work as expected (it only deletes the original image, not the variations).
- Trying to access the image does not work as it is the wrong path.

This would leave all files uploaded with a .jpg extension orphans and undeleted, and unable to be found.

# How to reproduce:

Follow the documentation and use a `JPEGField`:

```python
class MyModel(models.Model):
	image = JPEGField(delete_orphans=True, variations={ "large": (800, 600) })

```

Then use the admin to upload an image with a file extension of ".jpg".
The original file will be uploaded and resized as defined in the variations.
All resulting variations will have extension ".jpg" as the original file was already of type JPEG.

Try accessing the image using the shell: `python manage.py shell`:

```python
obj = MyModel.objects.first()
print(obj.image.large.path) # /absolute/path/image.jpeg (jpeg instead of jpg)
```

The attribute path returns the path to the files with extension ".jpeg" instead of ".jpg". But those files are stored with extension ".jpg", making them inaccessible.

## Possible culprit

It is possible that manually setting the path to ".jpeg" as it is done in the [source code](https://github.com/codingjoe/django-stdimage/blob/06ffda7c5ad29a0ebcdb76498f6d02b716337e16/stdimage/models.py#L296) might be the issue, although not certain.

Thank you for your help.

# Quick fix

Use a `StdImageField` for now.

**Comment by codingjoe** [comment]
Hi @tgdn,

Thank you for reaching out. However, I cannot reproduce the error you are describing. Neither manually, not in test.
Furthermore, the implementation explicitly sets the extension to `jpeg` and this behavior is tested.
If you can't find the file with that path in your storage, this may have other reasons. If you have additional information for me, maybe I can help you to resolve this issue.

Important sidenote, the original file, will keep the format and name it had before. FYI, a custom `upload_to` function could be a good place to look for errors.

Best
Joe
