### ISSUE TITLE
Extend variations with image format and options

### ISSUE THREAD

**Issue by martinsvoboda** [codingjoe/django-stdimage#276]
Thank you for this StdImage library. I am using it for several years, because its configuration and behaviour match my requirements more than other libraries (imagekit, easy-thumbnails). But I would like to generate WEBP variants or change quality of generated images #186.

### Suggested configuration

```python
class MyModel(models.Model):
    photo = StdImageField(
        upload_to="/mymodel/",
        variations={
            "detail": {"width": 140, "height": 210},
            "detail_webp": {"width": 140, "height": 210, "format"="WEBP", "options"={"quality": 80, "method": 6}},
        },
    )
```

Format and options would be optional. Options should match https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp

### How to save images to several formats?
For inspiration or as dependency we can use pilkit library https://github.com/matthewwithanm/pilkit/blob/09ffa2ad33318ae5fd3464655c14c7f01ffc2097/pilkit/utils.py#L165

I think this improvement can be pretty straightforward. Would you like to include this into StdImage? I'm happy to help with pull request.

**Comment by codingjoe** [comment]
Hi @martinsvoboda,

Thank you for your kind words. I am actually working on an update for this package that breaks WebP and soon AVIF support, including rendering proper `srcset` attributes for responsive pictures. I hope to find some time to finish the WebP part of this library later this week.

I will make sure to tag you for a review, OK?

Best Joe

**Comment by martinsvoboda** [comment]
Perfect, I am looking forward!

**Comment by codingjoe** [comment]
So, I wrote a whole new package, https://github.com/codingjoe/django-pictures
I believe this already has everything you're looking for. However, I'd appreciate if you give it a spin. It's still in alpha, but we'll get to a stable release asap.

I will close this issue for now, since I will deprecate this entire package, once we have a solid mirgraiton plan.
