### ISSUE TITLE
Deprecation warning from Pillow 9.1: rename of ANTIALIAS to LANCZOS

### ISSUE THREAD

**Issue by jmsmkn** [codingjoe/django-stdimage#290]
In Pillow 9.1 the `Image.ANTIALIAS` constant was deprecated for `Image.Resampling.LANCZOS` (https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#deprecations), the usage of this in `models.py` now raises a deprecation warning:

```
/usr/local/lib/python3.8/site-packages/stdimage/models.py:170: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
```

This will be removed next year in Pillow 10.0. The solution to this will depend on what versions of PIL you want to support:

- This library currently supports PIL 2.5 (2014).
- `PIL.Image.ANTIALIAS` is available in versions 2.5 through 9.x
- `PIL.Image.LANCZOS` is available in versions 2.7 though 9.x
- `PIL.Image.Resampling` was only added in PIL 9.1

**Comment by codingjoe** [comment]
Hi @jmsmkn,

Thank you for reaching out. As it happens, this package will be sunset as well and superseded by [django-pictures](https://github.com/codingjoe/django-pictures#readme). I plan to move django-pictures to production ready within the next couple of weeks. There will be no more feature updates of this package. I'd invite you to try out django-pictures and help us speed up our release roadmap.

Best,
Joe

**Comment by jmsmkn** [comment]
Good to know, thanks! I will check it out.
