### ISSUE TITLE
If PIL gets PIL.UnidentifiedImageError, then a 0kb file is uploaded to GCS

### ISSUE THREAD

**Issue by naveeda11** [codingjoe/django-stdimage#291]
Hello
I have configured my images to upload to GCS, but I assume this issue is generic. 
If PIL gets PIL.UnidentifiedImageError, then a 0kb file is uploaded to GCS. Is it possible to change the behavior so that no file is uploaded? 

```
File "/app/mymodel/mymodel.py", line 404, in import_item
    my_obj.main_image.save(
  File "/usr/local/lib/python3.9/site-packages/stdimage/models.py", line 47, in save
    self.render_variations()
  File "/usr/local/lib/python3.9/site-packages/stdimage/models.py", line 56, in render_variations
    self.render_variation(self.name, variation, replace, self.storage)
  File "/usr/local/lib/python3.9/site-packages/stdimage/models.py", line 76, in render_variation
    with Image.open(f) as img:
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <GoogleCloudFile: media/co/images/fake_image_file_name_d4869556>
```

**Comment by naveeda11** [comment]
Is it possible to switch the order of these lines  in render_variation ? 
with storage.open(file_name) as f:
            with Image.open(f) as img:

**Comment by codingjoe** [comment]
@naveeda11 thank you for reaching out. This package currently does not include any file validation. Preferably, this should be done as part of your form validation. We do ship with image size validators, but none that check of certain types.

If you want to contribute such a feature, may I recommend doing so in [django-pictures](https://github.com/codingjoe/django-pictures)? This package will be deprecated soon and superseeded by the more modern `django-pictures`.

Best! Joe
