### ISSUE TITLE
Support for WebP

### ISSUE THREAD

**Issue by thomashbrnrd** [codingjoe/django-stdimage#298]
Hello, I was wondering if you planned to add WebP support ?

Otherwise, could I create a PR in order to add it ?

**Comment by codingjoe** [comment]
Hi @thomashbrnrd,

I am guessing you read the migration note to django-pictures? I believe you'll find what you are looking (and more) over there.

Best Joe

**Comment by krystofbe** [comment]
if you don't want to use django-pictures (beta state e.g.) you can go with something like this:

```
class WEBPFieldFile(StdImageFieldFile):
    @classmethod
    def get_variation_name(cls, file_name, variation_name):
        path = super().get_variation_name(file_name, variation_name)
        path, ext = os.path.splitext(path)
        return "%s.webp" % path

    @classmethod
    def process_variation(cls, variation, image):
        """Process variation before actual saving."""
        save_kargs = {}
        file_format = "WEBP"
        save_kargs["format"] = file_format

        resample = variation["resample"]

        if variation["width"] is None:
            variation["width"] = image.size[0]

        if variation["height"] is None:
            variation["height"] = image.size[1]

        factor = 1
        while image.size[0] / factor > 2 * variation["width"] and image.size[1] * 2 / factor > 2 * variation["height"]:
            factor *= 2
        if factor > 1:
            image.thumbnail(
                (int(image.size[0] / factor), int(image.size[1] / factor)),
                resample=resample,
            )

        size = variation["width"], variation["height"]
        size = tuple(int(i) if i is not None else i for i in size)

        if variation["crop"]:
            image = ImageOps.fit(image, size, method=resample)
        else:
            image.thumbnail(size, resample=resample)

        save_kargs.update(variation["kwargs"])

        return image, save_kargs


class WEBPField(StdImageField):
    attr_class = WEBPFieldFile
```

**Comment by codingjoe** [comment]
> if you don't want to use django-pictures (beta state e.g.) you can go with something like this:
> 
> ```
> class WEBPFieldFile(StdImageFieldFile):
>     @classmethod
>     def get_variation_name(cls, file_name, variation_name):
>         path = super().get_variation_name(file_name, variation_name)
>         path, ext = os.path.splitext(path)
>         return "%s.webp" % path
> 
>     @classmethod
>     def process_variation(cls, variation, image):
>         """Process variation before actual saving."""
>         save_kargs = {}
>         file_format = "WEBP"
>         save_kargs["format"] = file_format
> 
>         resample = variation["resample"]
> 
>         if variation["width"] is None:
>             variation["width"] = image.size[0]
> 
>         if variation["height"] is None:
>             variation["height"] = image.size[1]
> 
>         factor = 1
>         while image.size[0] / factor > 2 * variation["width"] and image.size[1] * 2 / factor > 2 * variation["height"]:
>             factor *= 2
>         if factor > 1:
>             image.thumbnail(
>                 (int(image.size[0] / factor), int(image.size[1] / factor)),
>                 resample=resample,
>             )
> 
>         size = variation["width"], variation["height"]
>         size = tuple(int(i) if i is not None else i for i in size)
> 
>         if variation["crop"]:
>             image = ImageOps.fit(image, size, method=resample)
>         else:
>             image.thumbnail(size, resample=resample)
> 
>         save_kargs.update(variation["kwargs"])
> 
>         return image, save_kargs
> 
> 
> class WEBPField(StdImageField):
>     attr_class = WEBPFieldFile
> ```

@krystofbe thanks for the snippet. I wished it would be easier to extend StdImage. FYI django-pictures is in its RC phase now and the APIs are stable. I still highly recommend checking it out.
