### ISSUE TITLE
Package generates warning that ask for an upgrade, yet no stable upgrade path exists.

### ISSUE THREAD

**Issue by whyscream** [codingjoe/django-stdimage#300]
I started implementing the upgrade to `django-pictures` as described, but it seems that this package only has alpha releases, which additionally only support Python 3.10 or above. 

This means you cannot easily upgrade, but yet I have to look at the `DeprecationWarning` at each test run. My suggestion would be to remove the `DeprecationWarning` from the package (not from the documentation per se) until a stable upgrade path is available.

**Comment by codingjoe** [comment]
Hi @whyscream,

Thanks for reaching out. I believe you are making some excellent points. Yes, not everybody runs Python 3.10 everywhere. And not all features from stdimage were available in django-pictures. Therefore, I put in significant effort to resolve those issues over the weekend. 

Regarding the development, django-pictures is now released as `RC1` and will not receive any new features or API changes until the next major release. Therefore, it's stable enough to start migration. However, possible bugs, can only be found if the community starts adoption.

Now those are all concerns about django-pictures, not stdimage. Regarding the decoration warning. This package is deprecated! There's no sugar coating it. I don't have the time to maintain two packages for the same purpose. It is important to let engineers know that this package will not receive any updates unless security releated.

I hope my answer addresses all your questions and provides a bit of clarity for my reasoning.

Please don't hesitate to ask more questions, should you have any.

Best,
Joe
