### ISSUE TITLE
rendervariations command fails when custom manager is defined on abstract model

### ISSUE THREAD

**Issue by user0007** [codingjoe/django-stdimage#43]
django-stdimage==2.0.0
django==1.8

    class CustomManager(models.Manager):
        pass

    class BaseModel(models.Model):
        custom_objects = CustomManager()
    
        class Meta:
            abstract = True

    class MyModel(BaseModel):
        image = StdImageField(...)

    $ python manage.py rendervariations 'app.MyModel.image'
    AttributeError: type object 'MyModel' has no attribute 'objects'

You should replace this line https://github.com/codingjoe/django-stdimage/blob/master/stdimage/management/commands/rendervariations.py#L43 by:

    queryset = model_class._default_manager \

**Comment by codingjoe** [comment]
@user0007 I can't find any change in django that justifies that change. Objects, should still be available.
Can you provide any further information on how this happend?

**Comment by codingjoe** [comment]
Moreover, this command is actually being testing under django 1.8

**Comment by user0007** [comment]
Nope, it does not work when custom manger is defined on abstract model under different name than "objects" - because "objects" attribute is no longer available (maybe this is bug in Django?)

Example:

    class CustomManager(models.Manager):
         pass
     
     class BaseModel(models.Model):
         custom_objects = CustomManager()
     
         class Meta:
             abstract = True

     class MyModel(BaseModel):
         image = StdImageField(...)

    >>> MyModel.objects
    Traceback (most recent call last):
    self.model._meta.object_name,
    AttributeError: Manager isn't available; BaseModel is abstract

    >>> MyModel.custom_objects
    <myapp.models.CustomManager object at 0x9ee044c>

    $ python manage.py rendervariations 'myapp.MyModel.photo'
    Traceback (most recent call last):
      File "manage.py", line 8, in <module>
        execute_from_command_line(sys.argv)
      File "/home/myapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/home/myapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/myapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/myapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/home/myapp/local/lib/python2.7/site-packages/stdimage/management/commands/rendervariations.py", line 43, in handle
        queryset = model_class.objects \
      File "/home/myapp/local/lib/python2.7/site-packages/django/db/models/manager.py", line 264, in __get__
        self.model._meta.object_name,
    AttributeError: Manager isn't available; BaseModel is abstract

Anyway, Django developers recommend to use _default_manager - it is more generic.

**Comment by user0007** [comment]
I reported the same bug in factory_boy -> https://github.com/rbarrois/factory_boy/issues/201

They solved it: https://github.com/rbarrois/factory_boy/commit/0b5270eab393fad20faa7a6a9720af18c97b1773

**Comment by codingjoe** [comment]
@user0007 strange, I'll talk to some django dev later tonight. We need to get to the bottom of this.
Until than, feel free to commit a PR including a test maybe.

**Comment by codingjoe** [comment]
I fixed the bug and added a test myself. Thanks for the contribution!
