### ISSUE TITLE
Documentation on how to implement

### ISSUE THREAD

**Issue by drcursor** [codingjoe/django-stdimage#49]
Documentation states that "StdImageField works just like Django's own ImageField except that you can specify different sized variations.", but there is one huge difference, there is no widget. I've tried to make this work with a simple form and wasn't able to. Can you please supply a working example for the form template? Thanks!

**Comment by codingjoe** [comment]
@drcursor I don't get it. Why shouldn't there be a `forms.Field`? It inherits the from django's ImageField which inherits form FileField. FileField implements a method called `formfield`.
StdImage doesn't overwrite this method, therefore I don't see how this couldn't work.

Did you try swapping the field with a regular ImageField? Does it show?

**Comment by drcursor** [comment]
My bad - terribly sorry - I was using another custom django image field that had not only a model field but also a form widget. Closing in shame :pensive:

**Comment by codingjoe** [comment]
@drcursor never mind I hope stdimage is working for you.
