### ISSUE TITLE
Documentation issue: variations={'thumbnail': {'width': 100, 'height': 75}}) doesn't work.

### ISSUE THREAD

**Issue by pydanny** [codingjoe/django-stdimage#52]
Using the tuple system does work: `variations={'thumbnail': (100, 75)})`

**Comment by mpachas** [comment]
'with' or 'width'?

**Comment by codingjoe** [comment]
@pydanny it works for me.
https://github.com/codingjoe/django-stdimage/blob/master/tests/test_models.py#L92-L93

How can I reproduce the issue? Could you maybe write a failing test?
