### ISSUE TITLE
Possibility of rotating images before variations are created

### ISSUE THREAD

**Issue by GeorgeLubaretsi** [codingjoe/django-stdimage#55]
When stdimage creates variations, exif data is removed. Some devices (iOS) don't rotate an image, they only write EXIF orientation data. So after variations are created, it's impossible to set the correct orientation

**Comment by codingjoe** [comment]
Hi @GeorgeLubaretsi,

stdimage works file type independet, therefore we didn't add any special JPEG related code. But your problems is easily solved.

Take a look at http://stackoverflow.com/a/22063878/649951

You can pass your own renderer using the `render_variations` keyword argument. Check out the docs.
In your own renderer you can easily rotate yourself or copy exif information.

Cheers,
Joe
