### ISSUE TITLE
Image pathes on Windows

### ISSUE THREAD

**Issue by AntonOrlov** [codingjoe/django-stdimage#60]
Hello.

I have an issue with image pathes on windows os. Image pathes are incorrect:

images\8bf1763f53834fb4be962f416a51e2b9.index.jpg

i.e. variation name is jointed by os.path.sep which is wrong for my os.

**Comment by codingjoe** [comment]
@AntonOrlov what seems to be the problem with the image path above? What do you get, what should you get?

**Comment by codingjoe** [comment]
No reply
