### ISSUE TITLE
Variations attributes not preserved if object is saved in Django cache

### ISSUE THREAD

**Issue by baxeico** [codingjoe/django-stdimage#68]
Hi,
I'm using django-stdimage version 2.0.6. Consider the following example:

```
class Photo(models.Model):
    image = StdImageField(upload_to='photos', variations={
        'thumbnail': (500, 500),
    })
```

In a view I retrieve a Photo object and I want to cache it using default Django in-memory cache.

```
from django.core.cache import caches

cache = caches['default']
today_photo = cache.get('today_photo')
if today_photo is None:
    # Photo object not found in cache
    # retrieve it with some query
    today_photo = Photo.objects.filter(...)
    cache.set('today_photo', today_photo, 300)
    # this correctly logs the url of the thumbnail
    logger.debug('today_photo thumbnail: %s' % today_photo.image.thumbnail)
else:
    # Photo object is taken from cache
    # this is a server error: 'StdImageFieldFile' object has no attribute 'thumbnail'
    logger.debug('today_photo thumbnail: %s' % today_photo.image.thumbnail)
```

When retrieved from cache, the image field "lost" the thumbnail attribute. Is it a limitation of what can be saved in django cache or is it an issue you can address?

Thank you very much for your work!

**Comment by codingjoe** [comment]
Hi @baxeico
that is because the attribute is being set dynamically and is not properly serialised.

It must say, it's an odd use case. I can not recommend pickling an entire model instance.

As a quick fix you should just add the urls to the cache separately.

Cheers,
Joe

**Comment by baxeico** [comment]
No problem with the wontfix, I already implemented a workaround for my issue. I have to disagree on the odd use case, because pickling a model instance is a [perfectly legal operation](https://docs.djangoproject.com/en/1.8/ref/models/instances/#pickling-objects). Thank you very much for your work!

**Comment by baxeico** [comment]
Hi @frbry , I simply saved the url of the thumbnail variation on the cache, instead of saving the model instance, something like this:

```
today_photo_jpg_url = request.build_absolute_uri(today_photo.image.thumbnail.url)
cache.set('today_photo_jpg_url', today_photo_jpg_url)
```
