### ISSUE TITLE
error execute python manage.py rendervariations 'app_name.model_name.field_name' [--replace]

### ISSUE THREAD

**Issue by phardt** [codingjoe/django-stdimage#76]
in file rendervariations.py have in line 4 #import resource but don't find.

**Comment by codingjoe** [comment]
Hi @phardt which python version are you using?

**Comment by phardt** [comment]
3.4.4

**Comment by codingjoe** [comment]
[resource](https://docs.python.org/3.4/library/resource.html) is in python 2 and 3 including 3.4.4
You should check you python installation, but it's not a bug in this package. 3.4 is also covered by the CI suite.

Sorry that I can't be of more help, I hope you can find the issue.
