### ISSUE TITLE
Image quality automatically set to 75

### ISSUE THREAD

**Issue by amesbrown** [codingjoe/django-stdimage#77]
When rendering all variations, image quality is changed to 75. Specifically Image.save(quality=75) is implied. There should be an optional argument for each variation that specifies quality.

**Comment by codingjoe** [comment]
Hi @amesbrown ,

this questions was raised many times and yes, Pillow uses 75% JPEG compression by default. That isn't something StdImage specific.
The reason why there isn't a `quality` parameter is simple, only JPEG has one and StdImage supports all files supported by Pillow (PNG, BPM, JPEG2000, ...).

If you want to change the default, you can pass your own `render_variations` callable, which might change the behavior including the JPEG quality.

Besides that, 75% is a pretty good default.
