### ISSUE TITLE
How can I use default variation?

### ISSUE THREAD

**Issue by ba1dr** [codingjoe/django-stdimage#78]
I'd like to replace existing image field in my models with resized images by default. So without changing the rest of the code I would like to access `myproduct.image.url` to get url to already processed image instead of original one.

As I see from the code, default variation is not supported. Could you please add a variation named `default` to be returned by default instead of original one?

**Comment by codingjoe** [comment]
No, I'm sorry, but nether would this work, nor would I advice you to do such a thing. It would add implicit behavior. That's something you might want to avoid long term.

You can always overwrite the field tho and implement your own behavior. The StdImage code base should be good guidance to implement your own behavior.

Let me know if you have any further questions.
