### ISSUE TITLE
rendervariations doesn't use custom render_variations

### ISSUE THREAD

**Issue by vshab** [codingjoe/django-stdimage#80]
Hello!

When rerender variations through ```python manage.py rendervariations 'app_name.model_name.field_name' --replace``` stdimage use built-in ```render_variation``` function skipping ```render_variations``` parameter from ```StdImageField```.

How to reproduce:
1. Create the field in the model with custom render_variations function.
2. Create model instance.
3. Check result variations.
4. Run ```python manage.py rendervariations 'app_name.model_name.field_name' --replace```
5. Result variations will be rendered with ```render_variation``` from ```StdImageFieldFile``` not with function from 1.

**Comment by codingjoe** [comment]
Great! If I remember correctly this point was even pointed out to me on a talk last year. This is a good idea especially if you use a large set of celery workers.
