### ISSUE TITLE
Unknown command: 'rendervariations

### ISSUE THREAD

**Issue by raffone** [codingjoe/django-stdimage#95]
Hi, I'm trying to re-render the variantions using the `rendervariations` command from the readme but I get the following error:
```
Unknown command: 'rendervariations'
Type 'manage.py help' for usage.
```

Checking with `python manage.py help` doesn't show it in the available commands. What am I missing? Thanks!

**Comment by codingjoe** [comment]
Did you add 'stdimage' to `INSTALLED_APPS`?

**Comment by raffone** [comment]
Thats it, I had added `'django-stdimage'` instead of `'stdimage'`, everything worked well except this. Thanks!
